version: '3'

services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    expose:
      - 3306
      - 33060
    ports:
      - 3307:3306
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html



volumes:
  wordpress:
  dbdata:
